### PR TITLE
Disable install button when no packages are selected

### PR DESCRIPTION
**Pull request by shalomRachapudi**
Implemented using count() and itemAt() methods of QWidget::layout() - which is mainLayout (firstscreen.h/.cpp)

### CODE REVIEW

**Comment by antlarr** [comment]
I see you fixed what we talked about on irc, but I've noticed a few other things that could be changed:

PackageDetails::checkbox() shouldn't exist. Instead of a method that returns a checkbox only so that someone can check if the checkbox is checked or not, it should have a bool shouldBeInstalled() const; method that returns the Checked state of the QCheckbox.

Also, there's no need to store the layout as a member variable of FirstScreen, you can just use QWidget::layout() to get it at any point.

countCheckedPackages() is a bad name for a method that does more than counting checked packages. Maybe it could be renamed to checkPackagesInstallableState() or checkGeneralInstallableState() ?

In the same way, the PackageDetails::checkboxToggled(bool) signal should be changed to something like installableStateToggled(bool), don't you think? That way the PackageDetails interface doesn't expose that it's using a checkbox to the outside world.

There's a #include <QScrollArea> that can be removed. If you see the diff on this pull request, there are a few empty lines and such things that could be removed from the diff to make it nicer.

Finally, in the current FirstScreen::countCheckedPackages method there's no need to iterate always over all the PackageDetails objects. Once you find one, you can emit the signal and return, and if the for-loop finishes then it means all of them were false, so you can just emit the signal (with false parameter). That way you don't even need to count anything.

**Comment by shalomRachapudi** [comment]
have done the necessary changes. Thank you @antlarr

**Comment by antlarr** [comment]
Thanks, that's nearly perfect now. Just one very small issue :). In FirstScreen::checkPackagesInstallableState(), for each item in the layout, the layout is requested twice (in QWidget::layout()->count() and in QWidget::layout()->itemAt(i)->widget() ). Could you use a local layout variable and use that one in the loop ?

**Comment by antlarr** [comment]
Thanks!

**Pull request merged**
